#!/usr/bin/env python3
# ============================================================================
# LEGACY / FIRST-PUBLICATION ONLY. This paper is already published on Zenodo --
# re-running this mints a DUPLICATE concept DOI. The papers now live in
# ../../null-worldtube-private/papers/ (not this repo). To publish an UPDATED
# version use scripts/zenodo_newversion.py instead. See ../PUBLISHING.md.
# ============================================================================
"""Upload paper15_one_knot_all_forces.pdf to Zenodo and publish with DOI.

Usage:
    python3 scripts/zenodo_upload_paper15.py              # draft (no publish)
    python3 scripts/zenodo_upload_paper15.py --publish    # real upload + publish
    python3 scripts/zenodo_upload_paper15.py --sandbox    # test on sandbox
"""

import argparse
import os
import sys
import requests

TOKEN_FILE = os.path.expanduser("~/.zenodo_token")
PDF_PATH = os.path.join(
    os.path.dirname(__file__), "..", "..", "null-worldtube-private", "papers",
    "paper15_one_knot_all_forces.pdf",
)

SANDBOX_URL = "https://sandbox.zenodo.org/api"
PROD_URL = "https://zenodo.org/api"

METADATA = {
    "metadata": {
        "title": (
            "One Knot, All Forces: "
            "The Gravitational Constant from the "
            "Poincare Sphere of the Trefoil"
        ),
        "upload_type": "publication",
        "publication_type": "preprint",
        "description": (
            "Papers 13-14 derived eighty Standard Model observables "
            "from the trefoil knot T(2,3). This paper argues that "
            "(+1)-Dehn surgery on the trefoil--which produces the "
            "Poincare homology sphere S^3/2I and the icosahedral "
            "completion A_5 used for nuclear binding in companion "
            "Paper 17--also organises the integers appearing in the "
            "gravitational constant. The first 2I-invariant Laplacian "
            "eigenvalue on S^3/2I is lambda_1 = 168, which factorises "
            "two complementary ways: 168 = 8 x 21 (matching the "
            "spinor and adjoint dimensions of Spin(7) = B_3) and "
            "168 = 7 x 24 = |Irr(2T)| x |2T| via the McKay "
            "correspondence on the binary tetrahedral group. "
            "The integer 7 appears simultaneously as the spectral "
            "quotient (n_1+2)/2, as the McKay-node count on the "
            "extended E_6 diagram, and as the vector rep dimension "
            "of Spin(7); 2T embeds explicitly into Spin(7) via the "
            "octonion Clifford algebra Cl(0,7). These integers "
            "enter the proposed hierarchy "
            "m_e/m_Pl = (8/7)(1 + alpha/7) alpha^(21/2), where the "
            "exponent arises, under PSL(2,7)-equivariance, from a "
            "Wilson-line amplitude on the 21-edge complete graph "
            "K_7 (the Heawood map on the Heegaard torus of S^3/2I; "
            "21 = dim so(7)). The resulting gravitational constant "
            "G = (8/7)^2 (1+alpha/7)^2 alpha^21 hbar c / m_e^2 "
            "agrees numerically with CODATA at 0.013% using the "
            "NWT-derived alpha, or 0.029% using the measured alpha. "
            "Within the present accounting, no integer in the "
            "formula is introduced as an independent input beyond "
            "those already generated by the trefoil's surgery and "
            "spectrum; the cinquefoil T(2,5) and heptafoil T(2,7) "
            "appear as derived labels rather than additional free "
            "knots. The theory still contains a distinguished mass "
            "scale v_EW (equivalently m_e), treated as a reference "
            "scale setting the unit of measurement; the "
            "zero-parameter claim refers to the dimensionless "
            "content. Reproducibility: all analysis code (Laplacian "
            "eigenvalues on S^3/2I, the Cl(0,7) construction of "
            "2T in Spin(7), the one-loop BPS pipeline, the SU(N) "
            "robustness scan, and the G-formula verification) is "
            "available at https://github.com/JimGalasyn/null-worldtube."
        ),
        "creators": [
            {"name": "Galasyn, James P.", "affiliation": "Independent researcher"},
            {"name": "Théodore, Claude", "affiliation": "Anthropic, San Francisco, CA"},
        ],
        "keywords": [
            "gravitational constant",
            "hierarchy problem",
            "Poincare homology sphere",
            "trefoil knot",
            "Dehn surgery",
            "McKay correspondence",
            "binary tetrahedral group",
            "Spin(7)",
            "octonion Clifford algebra",
            "BPS vortex",
            "one-loop Casimir",
            "null worldtube",
            "null worldtube theory",
            "Heegaard torus",
            "K_7 complete graph",
            "Heawood map",
            "PSL(2,7)",
            "Kerr-Newman electron",
            "Volovik analog gravity",
        ],
        "related_identifiers": [
            {
                "identifier": "10.5281/zenodo.18891785",
                "relation": "isPartOf",
                "scheme": "doi",
            },
            {
                "identifier": "10.5281/zenodo.19654507",
                "relation": "continues",
                "scheme": "doi",
            },
            {
                "identifier": "10.5281/zenodo.19635239",
                "relation": "references",
                "scheme": "doi",
            },
            {
                "identifier": "10.5281/zenodo.19516386",
                "relation": "references",
                "scheme": "doi",
            },
        ],
        "license": "cc-by-4.0",
    }
}


def load_token():
    if not os.path.exists(TOKEN_FILE):
        print(f"Error: token file not found at {TOKEN_FILE}")
        sys.exit(1)
    with open(TOKEN_FILE) as f:
        return f.read().strip()


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--publish", action="store_true",
                        help="Publish after upload (makes DOI permanent)")
    parser.add_argument("--sandbox", action="store_true",
                        help="Use Zenodo sandbox for testing")
    args = parser.parse_args()

    token = load_token()
    base_url = SANDBOX_URL if args.sandbox else PROD_URL
    headers = {"Authorization": f"Bearer {token}"}

    pdf = os.path.abspath(PDF_PATH)
    if not os.path.exists(pdf):
        print(f"Error: PDF not found at {pdf}")
        sys.exit(1)

    # Step 1: Create empty deposition
    print("Creating deposition...")
    r = requests.post(f"{base_url}/deposit/depositions",
                      json={}, headers=headers)
    if r.status_code != 201:
        print(f"Error creating deposition: {r.status_code}\n{r.text}")
        sys.exit(1)

    dep = r.json()
    dep_id = dep["id"]
    bucket_url = dep["links"]["bucket"]
    print(f"  Deposition ID: {dep_id}")

    # Step 2: Upload PDF
    print(f"Uploading {os.path.basename(pdf)}...")
    with open(pdf, "rb") as fp:
        r = requests.put(f"{bucket_url}/{os.path.basename(pdf)}",
                         data=fp, headers=headers)
    if r.status_code not in (200, 201):
        print(f"Error uploading: {r.status_code}\n{r.text}")
        sys.exit(1)
    print("  Upload complete.")

    # Step 3: Set metadata
    print("Setting metadata...")
    r = requests.put(f"{base_url}/deposit/depositions/{dep_id}",
                     json=METADATA, headers=headers)
    if r.status_code != 200:
        print(f"Error setting metadata: {r.status_code}\n{r.text}")
        sys.exit(1)
    print("  Metadata set.")

    # Step 4: Publish (if requested)
    if args.publish:
        print("Publishing...")
        r = requests.post(
            f"{base_url}/deposit/depositions/{dep_id}/actions/publish",
            headers=headers,
        )
        if r.status_code != 202:
            print(f"Error publishing: {r.status_code}\n{r.text}")
            sys.exit(1)
        pub = r.json()
        doi = pub["doi"]
        doi_url = pub["doi_url"]
        print("\n  Published!")
        print(f"  DOI: {doi}")
        print(f"  URL: {doi_url}")
    else:
        prereserve = dep.get("metadata", {}).get("prereserve_doi", {})
        prereserve_doi = prereserve.get("doi", "N/A")
        print("\n  Draft created (not published).")
        print(f"  Pre-reserved DOI: {prereserve_doi}")
        print(f"  Edit/publish at: https://zenodo.org/deposit/{dep_id}")
        print("\n  Run with --publish to make it live.")


if __name__ == "__main__":
    main()
